id = "lat"
name = "LAT"
description = "Support for the LAT format."
version = "0.1.0"
schema_version = 1
authors = ["Fernando G. Vilar"]
repository = "https://github.com/vilarfg/zed-lat"

[grammars.lat]
repository = "https://github.com/vilarfg/tree-sitter-lat"
commit = "42badacd123666843399cdcc988ab464805cd912"
